"""
Email Service for Human Escalation
Uses Gmail SMTP to send escalation emails when a customer needs human assistance.
"""

import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from dotenv import load_dotenv

load_dotenv()


def send_escalation_email(user_email: str, summary: str) -> bool:
    """
    Send an escalation email to the company support team.

    Args:
        user_email: The customer's email address for follow-up.
        summary: LLM-generated summary of the conversation.

    Returns:
        True if sent successfully, False otherwise.
    """
    smtp_email = os.getenv("SMTP_EMAIL")
    smtp_password = os.getenv("SMTP_PASSWORD")
    escalation_email = os.getenv("ESCALATION_EMAIL")

    if not all([smtp_email, smtp_password, escalation_email]):
        raise ValueError(
            "Email configuration missing. Set SMTP_EMAIL, SMTP_PASSWORD, "
            "and ESCALATION_EMAIL in the .env file."
        )

    # Build the HTML email
    html_body = f"""
    <div style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <div style="background: linear-gradient(135deg, #6D55E9 0%, #9b8af2 100%); padding: 24px; border-radius: 12px 12px 0 0;">
            <h1 style="color: white; margin: 0; font-size: 22px;">🚨 Escalation Request — WebCraft Digital</h1>
        </div>
        <div style="background: #f9f8ff; padding: 24px; border: 1px solid #e8e4f8;">
            <p style="color: #333; margin-top: 0;">A customer has requested human assistance. The AI agent was unable to fully resolve their inquiry.</p>
            
            <div style="background: white; border-left: 4px solid #6D55E9; padding: 16px; border-radius: 4px; margin: 16px 0;">
                <h3 style="color: #6D55E9; margin-top: 0;">📧 Customer Email</h3>
                <p style="font-size: 16px; font-weight: 600;"><a href="mailto:{user_email}">{user_email}</a></p>
            </div>
            
            <div style="background: white; border-left: 4px solid #6D55E9; padding: 16px; border-radius: 4px; margin: 16px 0;">
                <h3 style="color: #6D55E9; margin-top: 0;">📝 Conversation Summary</h3>
                <p style="color: #444; line-height: 1.6; white-space: pre-line;">{summary}</p>
            </div>
            
            <p style="color: #888; font-size: 12px; margin-bottom: 0;">
                This email was automatically generated by the WebCraft Digital AI Support Agent.
            </p>
        </div>
    </div>
    """

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"🚨 Escalation: Customer needs help — {user_email}"
    msg["From"] = smtp_email
    msg["To"] = escalation_email
    msg.attach(MIMEText(html_body, "html"))

    try:
        with smtplib.SMTP("smtp.gmail.com", 587) as server:
            server.starttls()
            server.login(smtp_email, smtp_password)
            server.sendmail(smtp_email, escalation_email, msg.as_string())
        print(f"[EMAIL] Escalation email sent to {escalation_email}")
        return True
    except Exception as e:
        print(f"[EMAIL] Failed to send: {e}")
        raise
